[tool.poetry]
name = "sphinx-docs"
description = "ScyllaDB Documentation"
version = "0.2.1"
authors = ["ScyllaDB Documentation Contributors"]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "5.3"
pygments = "2.8.0"
recommonmark = "0.5.0"
sphinx-scylladb-theme = "~0.1.10"
sphinx-sitemap = "2.1.0"
sphinx-autobuild = "0.7.1"
Sphinx = "2.4.4"
sphinx-multiversion-scylla = "~0.2.6"

[tool.poetry.dev-dependencies]
pytest = "5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
