[tool.poetry]
name = "sphinx-docs"
description = "ScyllaDB Documentation"
version = "0.7.0"
authors = ["ScyllaDB Documentation Contributors"]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "6.0"
pygments = "2.11.2"
recommonmark = "0.7.1"
redirects_cli ="~0.1.2"
sphinx-scylladb-theme = "~1.3.1"
sphinx-sitemap = "2.2.0"
sphinx-autobuild = "2021.3.14"
Sphinx = "4.3.2"
sphinx-multiversion-scylla = "~0.2.11"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
